### ISSUE TITLE
Providing templates for creating metabolic reconstructions for bacterial strains

### ISSUE THREAD

**Issue by joel8484** [sysbiomelab/MIGRENE#1]
Hi, I am a new user of MIGRENE. The focus of my project is using automated tools to create metabolic network reconstructions from genome sequences. One of the tools is MIGRENE, from the provided schema for tutorials I am slightly confused as to which I can follow to create a reconstruction from scratch i.e, from an input file such as a FASTA genome file for the organism. Here I can see that we are using a bacterial catalogue to create a GEM and would like to know where can I retrieve one from. 

Thanks very much for your help in anticipation.
Regards,
Joel

**Comment by BidkhoriG** [comment]
Thank you for the email.
if you want to make the models from the scratch, you need to provide a metabolic model such as KBase metabolic model on your own model and an annotated catalog (annotation could be KO, E.C. number or KEGG reaction ID). the toolbox is developed to generate the models from a bacterial annotated catalog.
Best regards,
G Bidkhori

**Comment by BidkhoriG** [comment]
Hello, the toolbox got updated
