### ISSUE TITLE
detail Usage mannual

### ISSUE THREAD

**Issue by huangl07** [sysbiomelab/MIGRENE#2]
Hello,I have already finish all three step for my own data

but I have no idea how to get predition metabolism profile matrix

could you show me some suggestion?

**Comment by BidkhoriG** [comment]
Hello,
please specify in which the function(s) you faced any errors? 
Best regards,
Reza

**Comment by huangl07** [comment]
I am using my own metagenomic data to construct personalised community models. but when I ​finishi the three box code, I have get several indivials mats but I have no idea how to get the metabolism profile matrix?

the tree step is all down

**Comment by BidkhoriG** [comment]
the toolbox got updated.
